### PR TITLE
Create woocommerce-subscriptions-gifting-de_DE.po

### PR DESCRIPTION
**Pull request by kmindi**

### CODE REVIEW

**Comment by NickGreen** [comment]
Deutsch ist nicht meine Muttersprache, aber es sieht mir alle korrekt aus. Ist "duzen" normal für WordPress Plugins? Zum beispiel, "Du bist nicht {Name}?" anstatt "Seid Ihr nicht {Name}?"

Außer diese Frage, LGTM 👍

**Comment by kmindi** [comment]
I think it is common to use the informal Du/Dir and provide a second translation if needed for the formal Sie/Ihr (which is supposed to be postfixed then by `_formal`.

**Comment by NickGreen** [comment]
Not sure if this dropped off the radar, but I'm fine with the informal, I just wasn't sure how it worked. @LCmry any idea why this isn't passing checks?

**Comment by LCmry** [comment]
@NickGreen it looks like the build is throwing errors here:
```
$ bash tests/bin/travis.sh before
WooCommerce Installed
Cloning into '../woocommerce-subscriptions'...
remote: Repository not found.
fatal: Authentication failed for 'https://@github.com/Prospress/woocommerce-subscriptions.git/'
The command "bash tests/bin/travis.sh before" failed and exited with 128 during .
```
I reran a test to double check and the same issue occurred.  Perhaps it's a permissions issue when trying to clone Subscriptions, what do you think @james-allan ?

**Pull request merged**
